### PR TITLE
 Large change to resolve URLs with paths or versions.

### PR DESCRIPTION
**Pull request by millette**
Allows it to resolve:

* hostname.com/path
* hostname.com+4
* dat://hostname.com/path
* a1b[...]3c4/path (64 char key)
* a1b[...]3c4+4
* dat://a1b[...]3c4/path

Depends on <https://github.com/juliangruber/dat-encoding/pull/23>

<https://github.com/millette/dat-shell/issues/5> depends on these changes.

### CODE REVIEW

**Comment by millette** [comment]
The travis result is unexpected, I should test locally. It's working with node 6 (I didn't think it would) but fails as expected on node 4. As mentionned above, it depends on <https://github.com/juliangruber/dat-encoding/pull/23>

At home, I was only testing on node 8.

**Comment by millette** [comment]
[dat-encoding 5.0.1 was published](https://github.com/juliangruber/dat-encoding/pull/23#issuecomment-350747819). Running the tests again locally with node 4.8.7, 6.12.2, 8.9.3 and 9.2.1 and all tests pass.

**Comment by joehand** [comment]
I think this changes the DNS resolution to last. Is there a reason for that? (forgot to add update readme and add that as first in resolution order)

Re-ran travis and tests pass. Yay. We should add 8 here too though.

**Comment by millette** [comment]
The order is:

1. stringKey
2. Headers
3. json .key
4. dat-dns

Note that we skip tests 2 and 3 when either nets returns an error or the statusCode !== 200.

dat-dns happens last since if we ask for example.com/a-dat it may return a specific key at those headers or json (with dat .key). If there's nothing there, we do dat-dns for a more generic key.

In the readme, I can add the 4th step which is currently missing (dat-dns).

I can also add node 8 to travis in this patch or another if you prefer.

**Comment by joehand** [comment]
Thanks for getting through all this! Published as `2.1.0`

**Comment by millette** [comment]
You're very welcome :-)

**Pull request merged**
